### ISSUE TITLE
Support keyfiles

### ISSUE THREAD

**Issue by 4144414D** [4144414D/pytruecrypt#2]
Keyfiles are currently not supported, this should be included. 

![keyfile](https://cloud.githubusercontent.com/assets/7408210/8144036/8c8b2ea0-11c1-11e5-91f7-59c04c9fbc4e.png)

**Comment by redragonx** [comment]
Hi there,

Any updates on keyfile support? I need this feature to recover a 3tb partition with presentations and personal media. Is it possible to talk about this privately?

**Comment by 4144414D** [comment]
Nothing yet, tcplay may help you. You can contact me via email.

**Comment by 4144414D** [comment]
Basic keyfile support added.
